# Generated by Django 4.1.7 on 2023-04-03 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cathegory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cathegory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('img_path', models.CharField(max_length=350)),
                ('description', models.CharField(max_length=2000)),
                ('amount', models.IntegerField()),
            ],
            options={
                'db_table': 'equipment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RentAccounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=400)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('fact_start_date', models.DateTimeField(blank=True, null=True)),
                ('fact_end_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rent_accounting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('confidence_factor', models.IntegerField()),
                ('profile_approved', models.BooleanField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OldPriceOfEquipment',
            fields=[
                ('equipment', models.OneToOneField(db_column='equipment', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='BlackRockApp.equipment')),
                ('datetime', models.DateTimeField()),
                ('price', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'old_price_of_equipment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RentedCountableEquipment',
            fields=[
                ('accounting', models.OneToOneField(db_column='accounting', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='BlackRockApp.rentaccounting')),
                ('amount', models.IntegerField()),
                ('returned_amount', models.IntegerField()),
            ],
            options={
                'db_table': 'rented_countable_equipment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RentedEquipment',
            fields=[
                ('accounting', models.OneToOneField(db_column='accounting', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='BlackRockApp.rentaccounting')),
                ('deterioration', models.IntegerField()),
            ],
            options={
                'db_table': 'rented_equipment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UniqueEquipment',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='BlackRockApp.equipment')),
                ('deterioration', models.IntegerField()),
            ],
            options={
                'db_table': 'unique_equipment',
                'managed': False,
            },
        ),
    ]
